# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "14e68cb64a6de2412bbbbc0c95920a58"
name = "Bigly POD"
handle = "bigly-pod"
application_url = "https://bigly-pod-prod-77189af19854.herokuapp.com/"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dummy-store-usa.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_locations,read_merchant_managed_fulfillment_orders,read_orders,read_products,read_third_party_fulfillment_orders,write_assigned_fulfillment_orders,write_fulfillments,write_inventory,write_merchant_managed_fulfillment_orders,write_orders,write_products,write_third_party_fulfillment_orders"

[auth]
redirect_urls = [
  "https://bigly-pod-prod-77189af19854.herokuapp.com/auth/callback",
  "https://bigly-pod-prod-77189af19854.herokuapp.com/auth/shopify/callback",
  "https://bigly-pod-prod-77189af19854.herokuapp.com/api/auth/callback"
]

[webhooks]
api_version = "2023-04"

  [[webhooks.subscriptions]]
  uri = "https://us-central1-pod-bigly.cloudfunctions.net/gdpr/customer/request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "https://us-central1-pod-bigly.cloudfunctions.net/gdpr/store/customer/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://us-central1-pod-bigly.cloudfunctions.net/gdpr/store/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [
  "app_subscriptions/update",
  "app/uninstalled",
  "fulfillment_orders/cancellation_request_submitted"
]
  uri = "/webhooks"

[pos]
embedded = false
