# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e8075203c520dda8fcbe6fddf7931b5a"
name = "bigly-pod-frontend"
handle = "bigly-pod-frontend"
application_url = "https://chances-former-hart-modeling.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dummy-store-usa.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://chances-former-hart-modeling.trycloudflare.com/auth/callback",
  "https://chances-former-hart-modeling.trycloudflare.com/auth/shopify/callback",
  "https://chances-former-hart-modeling.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
